services:
    test:
        image: test-api:latest
        restart: always
        labels:
            # Habilitar Traefik para este servicio "test" en específico
            - traefik.enable=true
            # Definir el puerto dentro del servicio de Docker que usará
            - traefik.http.services.app.loadbalancer.server.port=80
            # Dominio que utilizará Traefik
            - traefik.http.routers.app.http.entrypoints=http
            - traefik.http.routers.app.http.rule=Host(`test.carlatino.com`)
            # Utilizar la red pública de Traefik
            - traefik.docker.networks=traefik-public
        networks:
            # Utilizar la red pública creada para compartir entre Traefik y
            # cualquier otro servicio que necesite estar disponible públicamente con HTTPS
            - traefik-public

networks:
    traefik-public:
        external: true
            